services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-site
    volumes:
      - .:/srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    command: jekyll serve --host 0.0.0.0 --livereload --force_polling --polling-interval 100ms
